# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='label',
            field=models.CharField(default='Product', max_length=50),
        ),
    ]
